# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "pxeserver" do |server|
    server.vm.synced_folder ".", "/vagrant", disabled: true
    server.vm.box = "centos/7"
    server.vm.host_name = "pxeserver"
    server.vm.network :private_network, ip: "10.0.0.20", virtualbox__intnet: "pxenet"
    server.vm.provider :virtualbox do |vb|
      vb.check_guest_additions = false
      vb.customize [
        "modifyvm", :id,
        "--memory", "512",
        "--natdnshostresolver1", "on"
      ]
    end
    server.vm.provision "shell", path: "./pxe_server.sh"
  end

  config.vm.define "pxeclient" do |client|
    client.vm.box = "centos/7"
    client.vm.host_name = "pxeclient"
    client.vm.network :private_network, ip: "10.0.0.21", virtualbox__intnet: "pxenet"
    client.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.check_guest_additions = false
      vb.customize [
        "modifyvm", :id,
        "--memory", "2048",
        "--graphicscontroller", "vmsvga",
        "--vram", "32",
        "--natdnshostresolver1", "on",
        "--nic1", "intnet",
        "--intnet1", "pxenet",
        "--nic2", "nat",
        "--boot1", "net",
        "--boot2", "none",
        "--boot3", "none",
        "--boot4", "none"
      ]
    end
  end

end

